# Generated by Django 5.1.1 on 2024-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('open_num', models.IntegerField(default=0)),
                ('recommend_num', models.IntegerField(default=0)),
                ('post_type', models.CharField(blank=True, default='None', max_length=20)),
                ('category', models.CharField(choices=[('Question', '질문'), ('Share', '정보 공유'), ('Team', '팀원 구인')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
