# Generated by Django 5.1.1 on 2024-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_contents', models.CharField(max_length=200)),
                ('chat_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('open_num', models.IntegerField(default=0)),
                ('recommend_num', models.IntegerField(default=0)),
                ('post_type', models.CharField(blank=True, default='None', max_length=20)),
                ('post_file', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('team_introduction', models.CharField(default='', max_length=500)),
                ('team_created', models.DateTimeField(auto_now_add=True)),
                ('team_category', models.CharField(choices=[('IT', 'IT'), ('문화', '문화'), ('수학', '수학'), ('과학', '과학'), ('언어', '언어'), ('경제', '경제'), ('문학/창작', '문학/창작'), ('사회', '사회'), ('기타', '기타')], max_length=50)),
            ],
        ),
    ]
