# Generated by Django 5.1.1 on 2024-09-29 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_apply_log',
            field=models.ManyToManyField(related_name='apply_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_masters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='team.team'),
        ),
        migrations.AddField(
            model_name='teampost',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_posts', to='team.team'),
        ),
        migrations.AddField(
            model_name='teampost',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teampostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='team.teampost'),
        ),
        migrations.AddField(
            model_name='teampostcomment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
